### ISSUE TITLE
QMK MSYS Compile Error

### ISSUE THREAD

**Issue by amknopes** [Taro-Hayashi/KillerWhale#22]
I just grabbed the latest killer whale duo code from [here](https://github.com/Taro-Hayashi/qmk_firmware/tree/tarohayashi/keyboards/tarohayashi/killerwhale/duo) and am getting a compiler error for it when using QMK MSYS:

![image](https://github.com/user-attachments/assets/ea90e121-1ad4-4be1-b78e-fe6035dc0142)

I'm not certain if this is an issue with the code or with my QMK installation

**Comment by Taro-Hayashi** [comment]
Hi, I'm sorry.
The code I have published is for qmk firmware version 0.24.8, but while I was playing around with it, I bumped it up to 0.25, and I think that's why it won't compile.
If you change the qmk version to 0.24.8, it will probably pass. I'm trying to catch up with the latest, so please wait a bit.

**Comment by amknopes** [comment]
okay I'll try downgrading my qmk, thanks!
